### ISSUE TITLE
Changes in lowerdir are not properly reflected

### ISSUE THREAD

**Issue by TheDcoder** [containers/fuse-overlayfs#320]
First of all, Thank you for making this fuse filesystem, it is very useful inside containers!

Unfortunately, the program has issues with properly reflecting updates to files in `lowerdir`, which makes it useless if the `lowerdir` is not static during operation.

I am using the experimental `timeout=0` option, it helps somewhat but that doesn't provide a full relief. I made a simple test container in `docker-compose` to reproduce the issues:
```yaml
version: "3.7"

services:
    test:
        image: alpine
        cap_add:
            - SYS_ADMIN # Required for mounting overlay
        devices:
            - "/dev/fuse"
        volumes:
            - /tmp/fuse-overlayfs/fuse-overlayfs-x86_64:/usr/local/bin/fuse-overlayfs # Latest binary from GitHub releases
            - ./overlay-test:/tmp/overlay-test
```

This is the shell session inside the container:
```
/tmp/overlay-test # apk add fuse3
/tmp/overlay-test # mkdir lower upper work mount
/tmp/overlay-test # echo "Test" > lower/foo
/tmp/overlay-test # fuse-overlayfs -o lowerdir=lower,upperdir=upper,workdir=work mount
/tmp/overlay-test # cat mount/foo
Test
/tmp/overlay-test # echo "Testing" > lower/bar # create bar
/tmp/overlay-test # cat mount/bar # bar isn't in the mount
cat: can't open 'mount/bar': No such file or directory
/tmp/overlay-test # fusermount3 -u mount
/tmp/overlay-test # fuse-overlayfs -o lowerdir=lower,upperdir=upper,workdir=work,timeout=0 mount
/tmp/overlay-test # cat mount/bar
Testing
/tmp/overlay-test # touch lower/bax # create bax
/tmp/overlay-test # cat mount/bax # bax is empty, which is correct
/tmp/overlay-test # echo "42" > lower/bax # write something to bax
/tmp/overlay-test # cat mount/bax # bax is still empty, not correct!
```

`timeout=0` fixes the issue of new files not being propagated, but any writes to those files are not reflected in the resulting overlay mount.

I am hoping that the issue is easy to fix, I don't mind a performance intensive solution as long as it works, I use this in non-production environments so it doesn't really matter.
